site_name: LED-Bug Docs
site_description: LED-Bug control your LED lights
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  logo: assets/logo.png
  favicon: images/favicon.png
  features:
   - navigation.tabs
   - navigation.sections
   - navigation.top
   - navigation.footer
   - toc.integrate
   - search.suggest
   - search.highlight
   - content.tabs
   - content.code.annotation
   - content.code.copy
  palette:
    primary: custom
nav:
  - Home: index.md
  - About: about.md
  - Contact: contact.md
  - Docs:
    - Getting Started: getting-started.md
    - Installation: installation.md
    - Usage: usage.md
    - Troubleshooting: troubleshooting.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - License: license.md


extra:
  generator: false
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/youyoubilly
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin-in
      link: https://www.linkedin.com/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/
  alternate:
    - name: English
      link: /
      lang: en
    # - name: 中文
    #   link: /zh/
    #   lang: zh
  consent:
    description: >- 
      <br><strong>Cookie Consent</strong><br>
      We use cookies to enhance your web browsing experience, analyse site effectiveness and needs. 
      By consenting, you help us improve our website. Thanks!<br>
      <br><strong>Cookie 授权说明</strong><br>
      我们使用Cookies以提升您的网页浏览体验，分析有效性和需求。您的同意将帮助我们改善网站。谢谢！
    # cookies:
    #   analytics:
    #     name: Google Analytics
    #     checked: false

copyright: Copyright &copy; 2023 LED-Bug

markdown_extensions:
  # Enables admonitions
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Enables emoji shortcodes like :+1: or :sunglasses:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - glightbox
  - search